name: metadata_god
description: Plugin for retrieving and writing audio tags/metadata from audio files
version: 1.0.0
repository: https://github.com/KRTirtho/frb_plugins/tree/main/packages/metadata_god

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2
  flutter_rust_bridge: 2.11.1
  uuid: ^4.4.0
  meta: ^1.11.0

dev_dependencies:
  ffigen: ^14.0.1
  lints: ^2.0.0
  test: ^1.21.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
